deaaprizal/cuyuniverse-forum

resources/css/app.css

Styling scrollbar dikit biar makin puturistik ehehe ✨

feat: add scrollbar styling

---

app/Http/Controllers/OuterController.php
app/Http/Controllers/PostsController.php
app/Models/Like.php
app/Models/Posts.php
database/migrations/2022_07_22_170636_create_likes_table.php
resources/js/Components/Homepage/PostList.jsx
routes/web.php

gw bikin fitur like, tapi tampilan button ga bagus di post comment

bikin fitur like

---

resources/js/Pages/Dashboard/Index.jsx

✨Change Style User Dahsboard

---

resources/js/Components/Homepage/PostsLists.jsx

✨Change Style Post Card

---

resources/js/Components/Homepage/PostList.jsx

Minor fix scroll tidak kembali ke atas ketika like

---

resources/css/app.css
resources/js/Pages/Dashboard/Setting.jsx

Upload photo dengan ngeklik photonya

follow me, mang... XD

---

app/Models/User.php
resources/css/app.css
resources/js/Components/Dashboard/CreatePost.jsx
resources/js/Components/Default/ApplicationLogo.jsx
resources/js/Components/Default/NavLink.jsx
resources/js/Components/Default/ResponsiveNavLink.jsx
resources/js/Components/Homepage/Announcement.jsx
resources/js/Components/Homepage/Hero.jsx
resources/js/Components/Homepage/PostList.jsx
resources/js/Pages/Author.jsx
resources/js/Pages/AuthorList.jsx
resources/js/Pages/Dashboard/Index.jsx
resources/js/Pages/Dashboard/MyPosts.jsx
resources/js/Pages/Dashboard/SavedPosts.jsx
resources/js/Pages/Dashboard/Setting.jsx
resources/js/Pages/Post.jsx
resources/js/Pages/Posts.jsx
resources/js/Pages/Teams.jsx

Fixing Bug Dark Mode✨

---

app/Http/Controllers/DashboardController.php
app/Models/User.php
database/migrations/2022_07_22_195337_create_notifications_table.php
resources/js/Pages/Dashboard/ChangePassword.jsx
resources/js/Pages/Dashboard/Setting.jsx
routes/web.php

Add feature **Change Password** in menu **Setting**.

Add feature change password

---

resources/js/Components/Default/NavLink.jsx
resources/js/Layouts/Authenticated.jsx
resources/js/Pages/Home.jsx

1. fix color navbar agar terlihat ketika dark mode
2. fix text color lihat postingan di home page
3. fix text color hover di auth navbar light

fix link color navbar if not actived

---

database/seeders/DatabaseSeeder.php
resources/css/app.css
resources/js/Components/Dashboard/CreatePost.jsx
resources/js/Components/Default/NotificationAlert.jsx
resources/js/Components/Default/ResponsiveNavLink.jsx
resources/js/Components/Homepage/DarkToggle.jsx
resources/js/Components/Homepage/PostList.jsx
resources/js/Layouts/Authenticated.jsx
resources/js/Layouts/Guest.jsx
resources/js/Pages/Auth/ConfirmPassword.jsx
resources/js/Pages/Auth/ForgotPassword.jsx
resources/js/Pages/Auth/Login.jsx
resources/js/Pages/Auth/Register.jsx
resources/js/Pages/Auth/ResetPassword.jsx
resources/js/Pages/Dashboard/Setting.jsx
resources/js/Pages/Posts.jsx

memperbaiki bug darkmode pada bagian navbar dan navbar dashboard, comment dan input untuk menuliskan komentar, termasuk input pada bagian autentikasi

peningkatan darmode

---

resources/js/Components/Homepage/DarkToggle.jsx
resources/js/Pages/Dashboard/ChangePassword.jsx
resources/js/Pages/Home.jsx

1. fix hover color lihat postingan
2. fix toggle darkmode color
- ketika dark mode
- ketika light mode

fix toggle dark mode and hover lihat postingan

---

app/Http/Controllers/AuthorController.php

reduce unnecessary query

---

resources/js/Pages/Dashboard/ChangePassword.jsx

Fix: remove console.log() in ChangePassword

---

app/Http/Controllers/PostsController.php

bikin notif like ke user yang ngepost dengan kondisi:
1. yg ngelike post bukan postnya sendiri
btw saya udh push sebelumnya, cuman kaya conflict ga ke-merge codingan saya

Send notifikasi like post

---

.gitignore
README.md

Menambahkan satu nodejs package manager lagi yaitu pnpm dan edit npm hanya cukup install dan jalankan.

chore: add pnpm & edit npm on README

---

resources/js/Components/Homepage/DarkToggle.jsx
resources/js/Pages/Dashboard/SavedPosts.jsx

fix: darkmode btn cursor pointer

---

app/Http/Controllers/PostsController.php
app/Notifications/UserMentioned.php
resources/js/Pages/Dashboard/Notification.jsx

Bikin fitur mention user di textbox post & comment, caranya dengan menuliskan @ kemudian username yang akan dimention, contoh: @baimtheelite
user yang di-mention akan mendapatkan notifikasi di dashboard
**Note:** Sebaiknya dibikin fitur autocomplete saat mau mention user, mungkin ntar akan nyusul atau teman2 bisa perbaiki. Thanks

Bikin fitur mention user di textbox post & comment

---

resources/js/Components/Dashboard/CreatePost.jsx
resources/js/Components/Homepage/PostList.jsx

fix button color dark mode and alert on dash board
- before
- after

fix button color dark mode on dashboard

---

resources/js/Layouts/Authenticated.jsx

Fix error fitur setting profile

---

resources/js/Components/Dashboard/CreatePost.jsx
resources/js/Components/Default/Dropdown.jsx
resources/js/Components/Homepage/PostList.jsx
resources/js/Layouts/Authenticated.jsx

memberikan smooth hover di button komentar

fix: hover transition on button comment

---

app/Http/Controllers/DashboardController.php
resources/js/Components/Homepage/PostsLists.jsx

fix: saved post author image

---

.vscode/settings.json
app/Http/Controllers/PostsController.php
app/Notifications/UserMentioned.php
phpunit.xml
tests/Feature/Notification/MentionNotificationTest.php

Btw itu ada unit test nya bang, kalo mau jalanin bisa pake command
```bash
php artisan test --testsuite=Feature --filter MentionNotificationTest
```

feat(mention_users): fix #201 performance issue on mentioning users

---

resources/js/Pages/AuthorList.jsx
resources/js/Pages/Posts.jsx

fix double request on first visit

---

resources/js/Layouts/Authenticated.jsx
resources/js/Layouts/Guest.jsx
resources/js/Pages/Teams.jsx

Semoga gak conflict  lagi ya bang

Removing border in navbar and add different color in user when their contributions is greater than 10

---

app/Models/User.php
resources/js/Components/Dashboard/CreatePost.jsx
resources/js/Pages/Teams.jsx

Reverts deaaprizal/laract9#224

Revert "fixing email verification"

---

app/Models/User.php
resources/js/Components/Dashboard/CreatePost.jsx
resources/js/Pages/Teams.jsx

Reverts deaaprizal/laract9#221

Revert "Dev"

---

resources/js/Components/Dashboard/IntegrationCLI.jsx
resources/js/Components/Default/ResponsiveNavLink.jsx
resources/js/Components/Homepage/PostList.jsx
resources/js/Layouts/Authenticated.jsx
resources/js/Layouts/Guest.jsx

- responsive dropdown
- before
- ipad mini
- ipXr
- after
- same device
- ipad mini
- ipXr
- padding button like and simpan fixed
- before
- after

Fix: responsive dropdown and padding button on coment

---

resources/js/Pages/Dashboard/SavedPosts.jsx
resources/js/Pages/Posts.jsx

fix: responsive posts filter

---

resources/js/Pages/AuthorList.jsx
resources/js/Pages/Posts.jsx

**Jika input pencarian diisi tapi tidak ada data pengguna sesuai pencarian yang diinginkan:**
**Jika input pencarian kosong dan query parameter `?page` terlalu jauh misal `?page=69696969696969` dan belum ada datanya atau datanya kosong:**

enhancement: alert message for handling empty data

---

resources/js/Components/Homepage/PostsLists.jsx

biar lebih rapih dan lebih enak dilihat (card nya terisi semua)

fix: word break on posts list description

---

resources/js/Components/Dashboard/CreatePost.jsx

change post styles✨

---

resources/js/Components/Homepage/PostsLists.jsx
resources/js/Pages/Posts.jsx

Gif preview: https://gyazo.com/41337cb729df2102b23e5142ad86248d

Smooth PostLists card on hover

---

database/factories/UserFactory.php
resources/js/Components/Dashboard/CreatePost.jsx
resources/js/Components/Homepage/PostsLists.jsx
resources/js/Pages/Author.jsx
resources/js/Pages/Posts.jsx
tests/Feature/Auth/RegistrationTest.php
tests/Feature/ExampleTest.php

Reverts deaaprizal/cuyuniverse-forum#266

Revert "fix: wrapper posts gap on author page"

---

resources/js/Components/Default/NotificationAlert.jsx
resources/js/Layouts/Authenticated.jsx
resources/js/Pages/Dashboard/MyPosts.jsx

- fixed notification width
- fixed toggle dark mode on authenticated layout responsive
- change button scroll to top
preview https://user-images.githubusercontent.com/48412599/183248283-6f2a166f-fa16-4f0b-91b6-49228982dbfc.mp4

fix: notification width and fix: layout authenticated toggle dark mode

---

package.json
resources/js/Pages/Posts.jsx

dari issue ini: https://github.com/deaaprizal/cuyuniverse/issues/191
bantu tes dong

tambah fitur infinity scroll
